apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
spec:
  selector:
    matchLabels:
      app: flask-pod
  replicas: 2
  template:
    metadata:
      labels:
        app: flask-pod
    spec:
      containers:
      - name: flask-frontend
        image: ruke04/flask-frontend:1.4
        ports:
        - containerPort: 5100
      - name: flask-backend
        image: ruke04/flask-backend:1.4
        ports:
        - containerPort: 5200          